#!/bin/zsh

if [ $# != 0 ]; then
	echo "usage: $0"
	return
fi

TMP=$(mktemp)
cat <<EOF >"$TMP"
**/*.go !**/*_test.go {
	prep: go build
}

**/*.go {
	prep: go test @dirmods
}
EOF
modd -f "$TMP" --noconf
